server:
  port: 9701
  servlet:
    path: /coco-api

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:15434/coco
    username: coco
    password: cocodev
  jpa.show-sql: false
  jpa.hibernate.ddl-auto: create
  jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
  jpa.properties.hibernate.temp.use_jdbc_metadata_defaults: false

logging.file: logs/coco.log
logging.file.max-history: 20

legalEntityRegistry:
  url: http://africa.nortal.com/company-registry/api/v1
personRegistry:
  url: http://africa.nortal.com/person-registry