server:
  port: 9701
  servlet:
    path: /coco-api

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6969/coco
    username: coco
    password: cocodev
  jpa.show-sql: false
  jpa.hibernate.ddl-auto: create
  jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
  jpa.properties.hibernate.temp.use_jdbc_metadata_defaults: false

logging.file: logs/coco.log
logging.file.max-history: 20

uxp:
  security-server: https://egov-demo-ss1.westeurope.cloudapp.azure.com/restapi
  instance: EGOV-EXAMPLE
  client:
    member-class: GOV
    member-code: M-JUSTICE
    subsystem-code: CREC-REG

person-registry:
  member-class: GOV
  member-code: M-HOMEAFFAIRS
  subsystem-code: POP-REG

business-registry:
  member-class: GOV
  member-code: M-HOMEAFFAIRS
  subsystem-code: BUSINESS-REG