server:
  port: 9701
  servlet:
    path: coco-api


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:15434/coco
    username: coco
    password: cocodev

logging.file: logs/coco.log
logging.file.max-history: 20
