version: "3.3"
services:
  postgres:
    image: postgres:11.0-alpine
    environment:
      POSTGRES_USER: coco
      POSTGRES_PASSWORD: cocodev
    ports:
    - 15434:5432
    volumes:
    - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: